name: secrets-security


on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  trigger-golden-pipeline:
    uses: markitos-it/markitos-it-project-goldens/.github/workflows/service-pipeline-secrets.yaml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GH_PAT_FOR_PRIVATE_REPOS: ${{ secrets.GH_PAT_FOR_PRIVATE_REPOS }}
