name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

jobs:
  call-security-and-publish:
    name: Execute Golden Service Pipeline
    permissions:
      contents: read
      id-token: write
    
    uses: markitos-it/markitos-it-project-goldens/.github/workflows/service-pipeline-secrets.yaml@main
    
    with:
      GO_VERSION: "1.26.3"

    secrets:
      GH_PAT_FOR_PRIVATE_REPOS: ${{ secrets.GH_PAT_FOR_PRIVATE_REPOS }}